2022-02-28 23:21:41 - root - ERROR -11_traceback模块: Traceback (most recent call last):
  File "/Users/jingzhaoyang/Desktop/2020Learn/code/python-code/1_4/11_traceback模块.py", line 21, in <module>
    print(1/0)
ZeroDivisionError: division by zero

